// Code generated by tui generate. DO NOT EDIT.
// Source: app.gsx

package views

import (
	"math/rand/v2"
	"time"

	"github.com/DanielJohn17/tui-chat/app/internal/tui/client"
	tui "github.com/grindlemire/go-tui"
)

type viewMode int

const (
	viewChats viewMode = iota
	viewProfile
	viewNewDM
)

type app struct {
	client        client.Client
	view          *tui.State[viewMode]
	selectedChat  *tui.State[int]
	draft         *tui.State[string]
	name          *tui.State[string]
	username      *tui.State[string]
	password      *tui.State[string]
	newDMName     *tui.State[string]
	newDMUsername *tui.State[string]
	profileEdit   *tui.State[bool]
	replyPending  *tui.State[int]
}

var mockReplies = []string{
	"Sounds great! Looking into it right now.",
	"Checked the pull request, everything looks solid.",
	"Let me test the websocket endpoint locally.",
	"Agreed, nice improvement on the UI.",
	"Deploying the latest build to staging 🚀",
	"Thanks for the update!",
	"👍 Got it!",
	"Looks fantastic!",
}

func App(c client.Client) *app {
	p := c.Profile()
	return &app{
		client:        c,
		view:          tui.NewState(viewChats),
		selectedChat:  tui.NewState(0),
		draft:         tui.NewState(""),
		name:          tui.NewState(p.Name),
		username:      tui.NewState(p.Username),
		password:      tui.NewState(p.Password),
		newDMName:     tui.NewState(""),
		newDMUsername: tui.NewState(""),
		profileEdit:   tui.NewState(false),
		replyPending:  tui.NewState(-1),
	}
}

func (a *app) KeyMap() tui.KeyMap {
	km := tui.KeyMap{
		tui.OnStop(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.KeyTab, func(ke tui.KeyEvent) { ke.App().FocusNext() }),
		tui.OnStop(tui.KeyTab.Shift(), func(ke tui.KeyEvent) { ke.App().FocusPrev() }),
		tui.OnStop(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.Rune('p'), func(ke tui.KeyEvent) { a.view.Set(viewProfile); a.profileEdit.Set(false) }),
		tui.OnStop(tui.Rune('n'), func(ke tui.KeyEvent) { a.view.Set(viewNewDM) }),
		tui.OnStop(tui.Rune('c'), func(ke tui.KeyEvent) { a.saveProfile(); a.view.Set(viewChats); a.profileEdit.Set(false) }),
	}
	if a.view.Get() == viewChats {
		chats := a.client.Chats()
		moveUp := func(ke tui.KeyEvent) {
			a.selectedChat.Update(func(v int) int {
				if v <= 0 {
					return len(chats) - 1
				}
				return v - 1
			})
		}
		moveDown := func(ke tui.KeyEvent) {
			a.selectedChat.Update(func(v int) int {
				if v >= len(chats)-1 {
					return 0
				}
				return v + 1
			})
		}
		km = append(km,
			tui.On(tui.KeyUp, moveUp),
			tui.On(tui.Rune('k'), moveUp),
			tui.On(tui.KeyDown, moveDown),
			tui.On(tui.Rune('j'), moveDown),
		)
	}
	if a.view.Get() == viewProfile && a.profileEdit.Get() {
	} else {
		km = append(km, tui.On(tui.KeyEscape, func(ke tui.KeyEvent) { a.view.Set(viewChats) }))
	}
	return km
}

func (a *app) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.OnTimer(2*time.Second, func() {
			if a.replyPending.Get() >= 0 {
				chatIdx := a.replyPending.Get()
				chats := a.client.Chats()
				if chatIdx >= 0 && chatIdx < len(chats) {
					chat := chats[chatIdx]
					reply := mockReplies[rand.IntN(len(mockReplies))]
					a.client.Send(chat.ID, reply)
				}
				a.replyPending.Set(-1)
			}
		}),
	}
}

func (a *app) profile() client.Profile {
	return a.client.Profile()
}

func (a *app) onSend() {
	a.replyPending.Set(a.selectedChat.Get())
}

func (a *app) saveProfile() {
	p := a.client.Profile()
	p.Name = a.name.Get()
	p.Username = a.username.Get()
	p.Password = a.password.Get()
	a.client.UpdateProfile(p)
	a.profileEdit.Set(false)
}

func (a *app) cancelProfile() {
	p := a.client.Profile()
	a.name.Set(p.Name)
	a.username.Set(p.Username)
	a.password.Set(p.Password)
	a.profileEdit.Set(false)
}

func (a *app) startNewDM() {
	name := a.newDMName.Get()
	username := a.newDMUsername.Get()
	if name == "" {
		name = "Anonymous User"
	}
	if username == "" {
		username = "anon"
	}
	a.client.AddChat(name, username)
	a.newDMName.Set("")
	a.newDMUsername.Set("")
	a.selectedChat.Set(len(a.client.Chats()) - 1)
	a.view.Set(viewChats)
}

func (a *app) cancelNewDM() {
	a.newDMName.Set("")
	a.newDMUsername.Set("")
	a.view.Set(viewChats)
}

func (a *app) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBackground(tui.NewStyle().Background(tui.Black)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithAlign(tui.AlignCenter),
		tui.WithGap(1),
	)
	__tui_3 := tui.New(
		tui.WithText("⚡ TUI CHAT"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("v1.2.0"),
		tui.WithTextStyle(tui.NewStyle().Dim().Foreground(tui.Cyan)),
	)
	__tui_2.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("•"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText("terminal direct messenger"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_6)
	__tui_1.AddChild(__tui_2)
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithAlign(tui.AlignCenter),
		tui.WithGap(2),
	)
	if a.view.Get() == viewChats {
		__tui_8 := tui.New(
			tui.WithText("[ Direct Messages ]"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
		)
		__tui_7.AddChild(__tui_8)
	} else if a.view.Get() == viewNewDM {
		__tui_9 := tui.New(
			tui.WithText("[ New Conversation ]"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Green)),
		)
		__tui_7.AddChild(__tui_9)
	} else {
		__tui_10 := tui.New(
			tui.WithText("[ Profile & Auth ]"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Yellow)),
		)
		__tui_7.AddChild(__tui_10)
	}
	__tui_1.AddChild(__tui_7)
	__tui_0.AddChild(__tui_1)
	__tui_11 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexGrow(1),
		tui.WithMinHeight(0),
		tui.WithGap(1),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_13 := app.Mount(a, 0, func() tui.Component {
		return Sidebar(a.client, a.selectedChat)
	})
	__tui_12.AddChild(__tui_13)
	if a.view.Get() == viewChats {
		__tui_14 := app.Mount(a, 1, func() tui.Component {
			return ChatPane(a.client, a.selectedChat, a.draft, a.onSend)
		})
		__tui_12.AddChild(__tui_14)
	} else if a.view.Get() == viewNewDM {
		__tui_15 := app.Mount(a, 2, func() tui.Component {
			return NewDM(a.newDMName, a.newDMUsername, a.startNewDM, a.cancelNewDM)
		})
		__tui_12.AddChild(__tui_15)
	} else {
		__tui_16 := app.Mount(a, 3, func() tui.Component {
			return Profile(a.name, a.username, a.password, a.profile().ID, a.profile().Token, a.profile().CreatedAt, a.profileEdit, a.saveProfile, a.cancelProfile)
		})
		__tui_12.AddChild(__tui_16)
	}
	__tui_0.AddChild(__tui_12)
	__tui_17 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_17)
	__tui_18 := app.Mount(a, 4, func() tui.Component {
		return StatusBar(a.view.Get(), a.profileEdit.Get())
	})
	__tui_0.AddChild(__tui_18)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (a *app) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*app)
	if !ok {
		return
	}
	a.client = f.client
}

func (a *app) UpdateProps(fresh tui.Component) {
	a.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*app)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (a *app) bindAppFields(app *tui.App) {
	if a.view != nil {
		a.view.BindApp(app)
	}
	if a.selectedChat != nil {
		a.selectedChat.BindApp(app)
	}
	if a.draft != nil {
		a.draft.BindApp(app)
	}
	if a.name != nil {
		a.name.BindApp(app)
	}
	if a.username != nil {
		a.username.BindApp(app)
	}
	if a.password != nil {
		a.password.BindApp(app)
	}
	if a.newDMName != nil {
		a.newDMName.BindApp(app)
	}
	if a.newDMUsername != nil {
		a.newDMUsername.BindApp(app)
	}
	if a.profileEdit != nil {
		a.profileEdit.BindApp(app)
	}
	if a.replyPending != nil {
		a.replyPending.BindApp(app)
	}
}

func (a *app) BindApp(app *tui.App) {
	a.bindAppFields(app)
}

var _ tui.AppBinder = (*app)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener     = (*app)(nil)
	_ tui.WatcherProvider = (*app)(nil)
)
