// Code generated by tui generate. DO NOT EDIT.
// Source: app.gsx

package views

import (
	"fmt"
	"math/rand/v2"
	"strings"
	"time"

	"github.com/DanielJohn17/tui-chat/app/internal/tui/client"
	tui "github.com/grindlemire/go-tui"
)

type viewMode int

const (
	viewChats viewMode = iota
	viewProfile
)

type app struct {
	client        client.Client
	view          *tui.State[viewMode]
	selectedChat  *tui.State[int]
	draft         *tui.State[string]
	name          *tui.State[string]
	username      *tui.State[string]
	password      *tui.State[string]
	newDMUsername *tui.State[string]
	showNewDM     *tui.State[bool]
	showHelp      *tui.State[bool]
	profileEdit   *tui.State[bool]
	replyPending  *tui.State[int]
}

var mockReplies = []string{
	"Sounds great! Looking into it right now.",
	"Checked the pull request, everything looks solid.",
	"Let me test the websocket endpoint locally.",
	"Agreed, nice improvement on the UI.",
	"Deploying the latest build to staging 🚀",
	"Thanks for the update!",
	"👍 Got it!",
	"Looks fantastic!",
}

func App(c client.Client) *app {
	p := c.Profile()
	return &app{
		client:        c,
		view:          tui.NewState(viewChats),
		selectedChat:  tui.NewState(0),
		draft:         tui.NewState(""),
		name:          tui.NewState(p.Name),
		username:      tui.NewState(p.Username),
		password:      tui.NewState(p.Password),
		newDMUsername: tui.NewState(""),
		showNewDM:     tui.NewState(false),
		showHelp:      tui.NewState(false),
		profileEdit:   tui.NewState(false),
		replyPending:  tui.NewState(-1),
	}
}

func (a *app) KeyMap() tui.KeyMap {
	// 1. Help Modal Active
	if a.showHelp.Get() {
		return tui.KeyMap{
			tui.OnStop(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
			tui.OnStop(tui.Rune('q'), func(ke tui.KeyEvent) { a.showHelp.Set(false) }),
			tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.showHelp.Set(false) }),
			tui.OnStop(tui.Rune('h'), func(ke tui.KeyEvent) { a.showHelp.Set(false) }),
			tui.OnStop(tui.Rune('?'), func(ke tui.KeyEvent) { a.showHelp.Set(false) }),
		}
	}

	// 2. New DM Modal Active
	if a.showNewDM.Get() {
		return tui.KeyMap{
			tui.OnStop(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
			tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.cancelNewDM() }),
		}
	}

	// 3. Profile View Active
	if a.view.Get() == viewProfile {
		if a.profileEdit.Get() {
			return tui.KeyMap{
				tui.OnStop(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
				tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.cancelProfile() }),
			}
		}
		return tui.KeyMap{
			tui.OnStop(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
			tui.OnStop(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
			tui.OnStop(tui.Rune('c'), func(ke tui.KeyEvent) { a.view.Set(viewChats) }),
			tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.view.Set(viewChats) }),
			tui.OnStop(tui.Rune('e'), func(ke tui.KeyEvent) { a.profileEdit.Set(true) }),
			tui.OnStop(tui.Rune('h'), func(ke tui.KeyEvent) { a.showHelp.Set(true) }),
			tui.OnStop(tui.Rune('?'), func(ke tui.KeyEvent) { a.showHelp.Set(true) }),
		}
	}

	// 4. Default Chat View
	chats := a.client.Chats()
	moveUp := func(ke tui.KeyEvent) {
		a.selectedChat.Update(func(v int) int {
			if v <= 0 {
				return len(chats) - 1
			}
			return v - 1
		})
	}
	moveDown := func(ke tui.KeyEvent) {
		a.selectedChat.Update(func(v int) int {
			if v >= len(chats)-1 {
				return 0
			}
			return v + 1
		})
	}

	return tui.KeyMap{
		tui.OnStop(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.KeyTab, func(ke tui.KeyEvent) { ke.App().FocusNext() }),
		tui.OnStop(tui.KeyTab.Shift(), func(ke tui.KeyEvent) { ke.App().FocusPrev() }),
		tui.OnStop(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.Rune('p'), func(ke tui.KeyEvent) { a.view.Set(viewProfile); a.profileEdit.Set(false) }),
		tui.OnStop(tui.Rune('n'), func(ke tui.KeyEvent) { a.showNewDM.Set(true) }),
		tui.OnStop(tui.Rune('h'), func(ke tui.KeyEvent) { a.showHelp.Set(true) }),
		tui.OnStop(tui.Rune('?'), func(ke tui.KeyEvent) { a.showHelp.Set(true) }),
		tui.On(tui.KeyUp, moveUp),
		tui.On(tui.Rune('k'), moveUp),
		tui.On(tui.KeyDown, moveDown),
		tui.On(tui.Rune('j'), moveDown),
	}
}

func (a *app) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.OnTimer(2*time.Second, func() {
			if a.replyPending.Get() >= 0 {
				chatIdx := a.replyPending.Get()
				chats := a.client.Chats()
				if chatIdx >= 0 && chatIdx < len(chats) {
					chat := chats[chatIdx]
					reply := mockReplies[rand.IntN(len(mockReplies))]
					a.client.Send(chat.ID, reply)
				}
				a.replyPending.Set(-1)
			}
		}),
	}
}

func (a *app) profile() client.Profile {
	return a.client.Profile()
}

func (a *app) onSend() {
	a.replyPending.Set(a.selectedChat.Get())
}

func (a *app) saveProfile() {
	p := a.client.Profile()
	p.Name = a.name.Get()
	p.Username = a.username.Get()
	p.Password = a.password.Get()
	a.client.UpdateProfile(p)
	a.profileEdit.Set(false)
}

func (a *app) cancelProfile() {
	p := a.client.Profile()
	a.name.Set(p.Name)
	a.username.Set(p.Username)
	a.password.Set(p.Password)
	a.profileEdit.Set(false)
}

func (a *app) startNewDM(username string) {
	username = strings.TrimSpace(strings.TrimPrefix(username, "@"))
	if username == "" {
		return
	}
	// Derive clean display name from username e.g. "alex" -> "Alex"
	displayName := strings.ToUpper(username[:1]) + username[1:]
	for _, ch := range a.client.Chats() {
		if strings.EqualFold(ch.Username, username) {
			// Select existing chat
			for i, c := range a.client.Chats() {
				if c.ID == ch.ID {
					a.selectedChat.Set(i)
					break
				}
			}
			a.newDMUsername.Set("")
			a.showNewDM.Set(false)
			a.view.Set(viewChats)
			return
		}
	}
	a.client.AddChat(fmt.Sprintf("%s", displayName), username)
	a.newDMUsername.Set("")
	a.showNewDM.Set(false)
	a.selectedChat.Set(len(a.client.Chats()) - 1)
	a.view.Set(viewChats)
}

func (a *app) cancelNewDM() {
	a.newDMUsername.Set("")
	a.showNewDM.Set(false)
}

func (a *app) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBackground(tui.NewStyle().Background(tui.Black)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithAlign(tui.AlignCenter),
		tui.WithGap(1),
	)
	__tui_3 := tui.New(
		tui.WithText("⚡ TUI CHAT"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("v1.2.0"),
		tui.WithTextStyle(tui.NewStyle().Dim().Foreground(tui.Cyan)),
	)
	__tui_2.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("•"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText("terminal direct messenger"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_6)
	__tui_1.AddChild(__tui_2)
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithAlign(tui.AlignCenter),
		tui.WithGap(2),
	)
	if a.view.Get() == viewChats {
		__tui_8 := tui.New(
			tui.WithText("[ Direct Messages ]"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
		)
		__tui_7.AddChild(__tui_8)
	} else {
		__tui_9 := tui.New(
			tui.WithText("[ Profile & Auth ]"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Yellow)),
		)
		__tui_7.AddChild(__tui_9)
	}
	__tui_1.AddChild(__tui_7)
	__tui_0.AddChild(__tui_1)
	__tui_10 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexGrow(1),
		tui.WithMinHeight(0),
		tui.WithGap(1),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_12 := app.Mount(a, 0, func() tui.Component {
		return Sidebar(a.client, a.selectedChat)
	})
	__tui_11.AddChild(__tui_12)
	if a.view.Get() == viewChats {
		__tui_13 := app.Mount(a, 1, func() tui.Component {
			return ChatPane(a.client, a.selectedChat, a.draft, a.onSend)
		})
		__tui_11.AddChild(__tui_13)
	} else {
		__tui_14 := app.Mount(a, 2, func() tui.Component {
			return Profile(a.name, a.username, a.password, a.profile().ID, a.profile().Token, a.profile().CreatedAt, a.profileEdit, a.saveProfile, a.cancelProfile)
		})
		__tui_11.AddChild(__tui_14)
	}
	__tui_0.AddChild(__tui_11)
	__tui_15 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_15)
	__tui_16 := app.Mount(a, 3, func() tui.Component {
		return StatusBar(a.view.Get(), a.profileEdit.Get())
	})
	__tui_0.AddChild(__tui_16)
	__tui_17 := app.Mount(a, 4, func() tui.Component {
		return HelpModal(a.showHelp)
	})
	__tui_0.AddChild(__tui_17)
	__tui_18 := app.Mount(a, 5, func() tui.Component {
		return NewDMModal(a.showNewDM, a.newDMUsername, a.startNewDM, a.cancelNewDM)
	})
	__tui_0.AddChild(__tui_18)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (a *app) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*app)
	if !ok {
		return
	}
	a.client = f.client
}

func (a *app) UpdateProps(fresh tui.Component) {
	a.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*app)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (a *app) bindAppFields(app *tui.App) {
	if a.view != nil {
		a.view.BindApp(app)
	}
	if a.selectedChat != nil {
		a.selectedChat.BindApp(app)
	}
	if a.draft != nil {
		a.draft.BindApp(app)
	}
	if a.name != nil {
		a.name.BindApp(app)
	}
	if a.username != nil {
		a.username.BindApp(app)
	}
	if a.password != nil {
		a.password.BindApp(app)
	}
	if a.newDMUsername != nil {
		a.newDMUsername.BindApp(app)
	}
	if a.showNewDM != nil {
		a.showNewDM.BindApp(app)
	}
	if a.showHelp != nil {
		a.showHelp.BindApp(app)
	}
	if a.profileEdit != nil {
		a.profileEdit.BindApp(app)
	}
	if a.replyPending != nil {
		a.replyPending.BindApp(app)
	}
}

func (a *app) BindApp(app *tui.App) {
	a.bindAppFields(app)
}

var _ tui.AppBinder = (*app)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener     = (*app)(nil)
	_ tui.WatcherProvider = (*app)(nil)
)
