// Code generated by tui generate. DO NOT EDIT.
// Source: help.gsx

package views

import (
	tui "github.com/grindlemire/go-tui"
)

type helpModal struct {
	open *tui.State[bool]
}

func HelpModal(open *tui.State[bool]) *helpModal {
	return &helpModal{open: open}
}

func (h *helpModal) Render(app *tui.App) *tui.Element {
	__tui_0 := app.MountPersistent(h, 0, func() tui.Component {
		return tui.NewModal(
			tui.WithModalOpen(h.open),
			tui.WithModalBackdrop("dim"),
			tui.WithModalElementOptions(tui.WithJustify(tui.JustifyCenter), tui.WithAlign(tui.AlignCenter)),
		)
	})
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(2),
		tui.WithGap(1),
		tui.WithBackground(tui.NewStyle().Background(tui.Black)),
		tui.WithWidth(52),
	)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_3 := tui.New(
		tui.WithText("Commands & Shortcuts"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("esc"),
		tui.WithTextStyle(tui.NewStyle().Dim().Foreground(tui.Yellow)),
	)
	__tui_2.AddChild(__tui_4)
	__tui_1.AddChild(__tui_2)
	__tui_5 := tui.New(
		tui.WithHR(),
	)
	__tui_1.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText("Suggested"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_8 := tui.New(
		tui.WithText("Switch conversation"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_7.AddChild(__tui_8)
	__tui_9 := tui.New(
		tui.WithText("j / k or ↑ / ↓"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_7.AddChild(__tui_9)
	__tui_1.AddChild(__tui_7)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_11 := tui.New(
		tui.WithText("New conversation"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText("n"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_10.AddChild(__tui_12)
	__tui_1.AddChild(__tui_10)
	__tui_13 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_14 := tui.New(
		tui.WithText("User profile & identity"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_13.AddChild(__tui_14)
	__tui_15 := tui.New(
		tui.WithText("p"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_13.AddChild(__tui_15)
	__tui_1.AddChild(__tui_13)
	__tui_16 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_17 := tui.New(
		tui.WithText("Focus message input"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_16.AddChild(__tui_17)
	__tui_18 := tui.New(
		tui.WithText("Tab"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_16.AddChild(__tui_18)
	__tui_1.AddChild(__tui_16)
	__tui_19 := tui.New(
		tui.WithHR(),
	)
	__tui_1.AddChild(__tui_19)
	__tui_20 := tui.New(
		tui.WithText("Actions & Navigation"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_20)
	__tui_21 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_22 := tui.New(
		tui.WithText("Send message"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_21.AddChild(__tui_22)
	__tui_23 := tui.New(
		tui.WithText("Enter"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_21.AddChild(__tui_23)
	__tui_1.AddChild(__tui_21)
	__tui_24 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_25 := tui.New(
		tui.WithText("Return to chats"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_24.AddChild(__tui_25)
	__tui_26 := tui.New(
		tui.WithText("c / Esc"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_24.AddChild(__tui_26)
	__tui_1.AddChild(__tui_24)
	__tui_27 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_28 := tui.New(
		tui.WithText("Edit user profile"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_27.AddChild(__tui_28)
	__tui_29 := tui.New(
		tui.WithText("e"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_27.AddChild(__tui_29)
	__tui_1.AddChild(__tui_27)
	__tui_30 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_31 := tui.New(
		tui.WithText("Toggle shortcuts help"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_30.AddChild(__tui_31)
	__tui_32 := tui.New(
		tui.WithText("h / ?"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
	)
	__tui_30.AddChild(__tui_32)
	__tui_1.AddChild(__tui_30)
	__tui_33 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_34 := tui.New(
		tui.WithText("Quit messenger"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_33.AddChild(__tui_34)
	__tui_35 := tui.New(
		tui.WithText("q"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_33.AddChild(__tui_35)
	__tui_1.AddChild(__tui_33)
	__tui_0.AddChild(__tui_1)

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (h *helpModal) bindAppFields(app *tui.App) {
	if h.open != nil {
		h.open.BindApp(app)
	}
}

func (h *helpModal) BindApp(app *tui.App) {
	h.bindAppFields(app)
}

var _ tui.AppBinder = (*helpModal)(nil)
