// Code generated by tui generate. DO NOT EDIT.
// Source: newdm.gsx

package views

import (
	tui "github.com/grindlemire/go-tui"
)

type newDM struct {
	name     *tui.State[string]
	username *tui.State[string]
	onStart  func()
	onCancel func()
}

func NewDM(name *tui.State[string], username *tui.State[string], onStart func(), onCancel func()) *newDM {
	return &newDM{
		name:     name,
		username: username,
		onStart:  onStart,
		onCancel: onCancel,
	}
}

func (n *newDM) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { n.onCancel() }),
		tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { n.onStart() }),
	}
}

func (n *newDM) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithGap(1),
		tui.WithPaddingTRBL(0, 2, 0, 2),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 0, 0, 0),
	)
	__tui_2 := tui.New(
		tui.WithText("◈ START NEW CONVERSATION"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("[ POST /api/v1/conversations ]"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPaddingTRBL(1, 1, 1, 1),
		tui.WithWidth(60),
	)
	__tui_6 := tui.New(
		tui.WithText("Recipient Display Name"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
	)
	__tui_5.AddChild(__tui_6)
	__tui_7 := app.MountPersistent(n, 0, func() tui.Component {
		return tui.NewInput(
			tui.WithInputValue(n.name),
			tui.WithInputPlaceholder("e.g. David Kim"),
			tui.WithInputBorder(tui.BorderRounded),
			tui.WithInputWidth(50),
			tui.WithInputFocusColor(tui.Magenta),
			tui.WithInputAutoFocus(true),
		)
	})
	__tui_5.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("Recipient Username"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
	)
	__tui_5.AddChild(__tui_8)
	__tui_9 := app.MountPersistent(n, 1, func() tui.Component {
		return tui.NewInput(
			tui.WithInputValue(n.username),
			tui.WithInputPlaceholder("e.g. david"),
			tui.WithInputBorder(tui.BorderRounded),
			tui.WithInputWidth(50),
			tui.WithInputFocusColor(tui.Magenta),
		)
	})
	__tui_5.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithPaddingTRBL(1, 0, 0, 0),
	)
	__tui_11 := tui.New(
		tui.WithText("[Enter] Start Chat"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText("•"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_10.AddChild(__tui_12)
	__tui_13 := tui.New(
		tui.WithText("[Esc] Cancel"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_10.AddChild(__tui_13)
	__tui_5.AddChild(__tui_10)
	__tui_14 := tui.New(
		tui.WithPaddingTRBL(1, 0, 0, 0),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_15 := tui.New(tui.WithText("Creates or fetches direct message thread"))
	__tui_14.AddChild(__tui_15)
	__tui_16 := tui.New(tui.WithText("peer user ID"))
	__tui_14.AddChild(__tui_16)
	__tui_5.AddChild(__tui_14)
	__tui_0.AddChild(__tui_5)

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (n *newDM) bindAppFields(app *tui.App) {
	if n.name != nil {
		n.name.BindApp(app)
	}
	if n.username != nil {
		n.username.BindApp(app)
	}
}

func (n *newDM) BindApp(app *tui.App) {
	n.bindAppFields(app)
}

var _ tui.AppBinder = (*newDM)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*newDM)(nil)
)
