// Code generated by tui generate. DO NOT EDIT.
// Source: profile.gsx

package views

import (
	tui "github.com/grindlemire/go-tui"
)

type profile struct {
	username    *tui.State[string]
	accountCode *tui.State[string]
	password    *tui.State[string]
	editMode    *tui.State[bool]
	onSave      func()
	onCancel    func()
}

func Profile(username *tui.State[string], accountCode *tui.State[string], password *tui.State[string], editMode *tui.State[bool], onSave func(), onCancel func()) *profile {
	return &profile{
		username:    username,
		accountCode: accountCode,
		password:    password,
		editMode:    editMode,
		onSave:      onSave,
		onCancel:    onCancel,
	}
}

func (p *profile) KeyMap() tui.KeyMap {
	if p.editMode.Get() {
		return tui.KeyMap{
			tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { p.onCancel() }),
			tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { p.onSave() }),
		}
	}
	return tui.KeyMap{
		tui.On(tui.Rune('e'), func(ke tui.KeyEvent) { p.editMode.Set(true) }),
	}
}

func (p *profile) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithGap(1),
		tui.WithPaddingTRBL(0, 2, 0, 2),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
		tui.WithFlexShrink(0),
	)
	__tui_2 := tui.New(
		tui.WithText("User Profile"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	if p.editMode.Get() {
		__tui_3 := tui.New(
			tui.WithText("[Editing Mode]"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_1.AddChild(__tui_3)
	} else {
		__tui_4 := tui.New(
			tui.WithText("Pressto edit"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_4)
	}
	__tui_0.AddChild(__tui_1)
	__tui_5 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_5)
	if p.editMode.Get() {
		__tui_6 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithGap(1),
		)
		__tui_7 := tui.New(
			tui.WithText("Username"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
		)
		__tui_6.AddChild(__tui_7)
		__tui_8 := app.MountPersistent(p, 0, func() tui.Component {
			return tui.NewInput(
				tui.WithInputValue(p.username),
				tui.WithInputPlaceholder("Enter username..."),
				tui.WithInputBorder(tui.BorderRounded),
				tui.WithInputWidth(45),
				tui.WithInputFocusColor(tui.Cyan),
				tui.WithInputAutoFocus(true),
			)
		})
		__tui_6.AddChild(__tui_8)
		__tui_9 := tui.New(
			tui.WithText("Account Code"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
		)
		__tui_6.AddChild(__tui_9)
		__tui_10 := app.MountPersistent(p, 1, func() tui.Component {
			return tui.NewInput(
				tui.WithInputValue(p.accountCode),
				tui.WithInputPlaceholder("Enter account code..."),
				tui.WithInputBorder(tui.BorderRounded),
				tui.WithInputWidth(45),
				tui.WithInputFocusColor(tui.Cyan),
			)
		})
		__tui_6.AddChild(__tui_10)
		__tui_11 := tui.New(
			tui.WithText("Password"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
		)
		__tui_6.AddChild(__tui_11)
		__tui_12 := app.MountPersistent(p, 2, func() tui.Component {
			return tui.NewInput(
				tui.WithInputValue(p.password),
				tui.WithInputPlaceholder("Enter password..."),
				tui.WithInputBorder(tui.BorderRounded),
				tui.WithInputWidth(45),
				tui.WithInputFocusColor(tui.Cyan),
			)
		})
		__tui_6.AddChild(__tui_12)
		__tui_13 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(2),
			tui.WithPaddingTRBL(1, 0, 0, 0),
		)
		__tui_14 := tui.New(
			tui.WithText("[Enter] Save Changes"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
		)
		__tui_13.AddChild(__tui_14)
		__tui_15 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_13.AddChild(__tui_15)
		__tui_16 := tui.New(
			tui.WithText("[Esc] Cancel"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_13.AddChild(__tui_16)
		__tui_6.AddChild(__tui_13)
		__tui_0.AddChild(__tui_6)
	} else {
		__tui_17 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithGap(1),
		)
		__tui_18 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderSingle),
			tui.WithPaddingTRBL(0, 2, 0, 2),
			tui.WithWidth(48),
		)
		__tui_19 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
		)
		__tui_20 := tui.New(
			tui.WithText("Account Information"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
		)
		__tui_19.AddChild(__tui_20)
		__tui_21 := tui.New(
			tui.WithText("● Active"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		__tui_19.AddChild(__tui_21)
		__tui_18.AddChild(__tui_19)
		__tui_22 := tui.New(
			tui.WithHR(),
		)
		__tui_18.AddChild(__tui_22)
		__tui_23 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
		)
		__tui_24 := tui.New(
			tui.WithText("Username:"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_23.AddChild(__tui_24)
		__tui_25 := tui.New(
			tui.WithText(p.username.Get()),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
		)
		__tui_23.AddChild(__tui_25)
		__tui_18.AddChild(__tui_23)
		__tui_26 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
		)
		__tui_27 := tui.New(
			tui.WithText("Account Code:"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_26.AddChild(__tui_27)
		__tui_28 := tui.New(
			tui.WithText(p.accountCode.Get()),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
		)
		__tui_26.AddChild(__tui_28)
		__tui_18.AddChild(__tui_26)
		__tui_29 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
		)
		__tui_30 := tui.New(
			tui.WithText("Password:"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_29.AddChild(__tui_30)
		__tui_31 := tui.New(
			tui.WithText("••••••••"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_29.AddChild(__tui_31)
		__tui_18.AddChild(__tui_29)
		__tui_17.AddChild(__tui_18)
		__tui_32 := tui.New(
			tui.WithText("Press [e] to edit profile details"),
			tui.WithPaddingTRBL(1, 0, 0, 0),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_17.AddChild(__tui_32)
		__tui_0.AddChild(__tui_17)
	}

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (p *profile) bindAppFields(app *tui.App) {
	if p.username != nil {
		p.username.BindApp(app)
	}
	if p.accountCode != nil {
		p.accountCode.BindApp(app)
	}
	if p.password != nil {
		p.password.BindApp(app)
	}
	if p.editMode != nil {
		p.editMode.BindApp(app)
	}
}

func (p *profile) BindApp(app *tui.App) {
	p.bindAppFields(app)
}

var _ tui.AppBinder = (*profile)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*profile)(nil)
)
