// Code generated by tui generate. DO NOT EDIT.
// Source: profile.gsx

package views

import (
	tui "github.com/grindlemire/go-tui"
)

type profile struct {
	username    *tui.State[string]
	accountCode *tui.State[string]
	password    *tui.State[string]
	editMode    *tui.State[bool]
	onSave      func()
	onCancel    func()
}

func Profile(username *tui.State[string], accountCode *tui.State[string], password *tui.State[string], editMode *tui.State[bool], onSave func(), onCancel func()) *profile {
	return &profile{
		username:    username,
		accountCode: accountCode,
		password:    password,
		editMode:    editMode,
		onSave:      onSave,
		onCancel:    onCancel,
	}
}

func (p *profile) KeyMap() tui.KeyMap {
	if p.editMode.Get() {
		return tui.KeyMap{
			tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { p.onCancel() }),
			tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { p.onSave() }),
		}
	}
	return tui.KeyMap{
		tui.On(tui.Rune('e'), func(ke tui.KeyEvent) { p.editMode.Set(true) }),
	}
}

func (p *profile) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithGap(1),
		tui.WithPaddingTRBL(0, 2, 0, 2),
	)
	__tui_1 := tui.New(
		tui.WithText("Profile"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	if p.editMode.Get() {
		__tui_2 := tui.New(
			tui.WithText("Username"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_2)
		__tui_3 := app.MountPersistent(p, 0, func() tui.Component {
			return tui.NewInput(
				tui.WithInputValue(p.username),
				tui.WithInputPlaceholder("Username"),
				tui.WithInputBorder(tui.BorderRounded),
			)
		})
		__tui_0.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText("Account Code"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_4)
		__tui_5 := app.MountPersistent(p, 1, func() tui.Component {
			return tui.NewInput(
				tui.WithInputValue(p.accountCode),
				tui.WithInputPlaceholder("Account Code"),
				tui.WithInputBorder(tui.BorderRounded),
			)
		})
		__tui_0.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText("Password"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_6)
		__tui_7 := app.MountPersistent(p, 2, func() tui.Component {
			return tui.NewInput(
				tui.WithInputValue(p.password),
				tui.WithInputPlaceholder("Password"),
				tui.WithInputBorder(tui.BorderRounded),
			)
		})
		__tui_0.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText("Tab between fields | Enter save | Esc cancel"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Dim()),
		)
		__tui_0.AddChild(__tui_8)
	} else {
		__tui_9 := tui.New(
			tui.WithText("Username"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_9)
		__tui_10 := tui.New(
			tui.WithText(p.username.Get()),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_0.AddChild(__tui_10)
		__tui_11 := tui.New(
			tui.WithText("Account Code"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_11)
		__tui_12 := tui.New(
			tui.WithText(p.accountCode.Get()),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_0.AddChild(__tui_12)
		__tui_13 := tui.New(
			tui.WithText("Password"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_13)
		__tui_14 := tui.New(
			tui.WithText("********"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_0.AddChild(__tui_14)
		__tui_15 := tui.New(
			tui.WithText("Press e to edit"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_15)
	}

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (p *profile) bindAppFields(app *tui.App) {
	if p.username != nil {
		p.username.BindApp(app)
	}
	if p.accountCode != nil {
		p.accountCode.BindApp(app)
	}
	if p.password != nil {
		p.password.BindApp(app)
	}
	if p.editMode != nil {
		p.editMode.BindApp(app)
	}
}

func (p *profile) BindApp(app *tui.App) {
	p.bindAppFields(app)
}

var _ tui.AppBinder = (*profile)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*profile)(nil)
)
