// Code generated by tui generate. DO NOT EDIT.
// Source: sidebar.gsx

package views

import (
	"github.com/DanielJohn17/tui-chat/app/internal/tui/client"
	tui "github.com/grindlemire/go-tui"
)

type SidebarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SidebarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SidebarView) GetRoot() *tui.Element { return v.Root }

func (v *SidebarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SidebarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SidebarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SidebarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SidebarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SidebarView)(nil)

var _ tui.AppUnbinder = (*SidebarView)(nil)

var _ tui.PropsUpdater = (*SidebarView)(nil)

func Sidebar(c client.Client, selectedChat *tui.State[int]) *SidebarView {
	var view SidebarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderSingle),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithWidth(22),
	)
	__tui_1 := tui.New(
		tui.WithText("Chats"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	__loop_0_style := __tui_0.LayoutStyle()
	__loop_0 := tui.New(tui.WithDirection(__loop_0_style.Direction), tui.WithGap(__loop_0_style.Gap))
	__tui_0.AddChild(__loop_0)
	__update___loop_0 := func() {
		__loop_0.RemoveAllChildren()
		for i, ch := range c.Chats() {
			_ = i
			if i == selectedChat.Get() {
				__tui_3 := tui.New(
					tui.WithText("> "+ch.Name),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
				)
				__loop_0.AddChild(__tui_3)
			} else {
				__tui_4 := tui.New(
					tui.WithText("  "+ch.Name),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__loop_0.AddChild(__tui_4)
			}
		}
	}
	__update___loop_0()
	selectedChat.Bind(func(_ int) { __update___loop_0() })

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SidebarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
