// Code generated by tui generate. DO NOT EDIT.
// Source: statusbar.gsx

package views

import (
	tui "github.com/grindlemire/go-tui"
)

type StatusBarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *StatusBarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *StatusBarView) GetRoot() *tui.Element { return v.Root }

func (v *StatusBarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *StatusBarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *StatusBarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *StatusBarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*StatusBarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*StatusBarView)(nil)

var _ tui.AppUnbinder = (*StatusBarView)(nil)

var _ tui.PropsUpdater = (*StatusBarView)(nil)

func StatusBar(v viewMode, editing bool) *StatusBarView {
	var view StatusBarView
	var watchers []tui.Watcher

	var __tui_0 *tui.Element
	if v == viewChats {
		__tui_1 := tui.New(
			tui.WithFlexShrink(0),
			tui.WithBackground(tui.NewStyle().Background(tui.Blue)),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
		)
		__tui_2 := tui.New(
			tui.WithText("⌨ ↑/↓ j/k nav"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_1.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText("Tab"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_1.AddChild(__tui_4)
		__tui_5 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_1.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText("p profile"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_1.AddChild(__tui_6)
		__tui_7 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_1.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText("Enter send"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_1.AddChild(__tui_8)
		__tui_9 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_1.AddChild(__tui_9)
		__tui_10 := tui.New(
			tui.WithText("q quit"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_1.AddChild(__tui_10)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else if editing {
		__tui_11 := tui.New(
			tui.WithFlexShrink(0),
			tui.WithBackground(tui.NewStyle().Background(tui.Green)),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Black)),
		)
		__tui_12 := tui.New(
			tui.WithText("✎ Editing Profile"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_11.AddChild(__tui_12)
		__tui_13 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_11.AddChild(__tui_13)
		__tui_14 := tui.New(
			tui.WithText("Tab field"),
		)
		__tui_11.AddChild(__tui_14)
		__tui_15 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_11.AddChild(__tui_15)
		__tui_16 := tui.New(
			tui.WithText("Enter save"),
		)
		__tui_11.AddChild(__tui_16)
		__tui_17 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_11.AddChild(__tui_17)
		__tui_18 := tui.New(
			tui.WithText("Esc cancel"),
		)
		__tui_11.AddChild(__tui_18)
		if __tui_0 == nil {
			__tui_0 = __tui_11
		}
	} else {
		__tui_19 := tui.New(
			tui.WithFlexShrink(0),
			tui.WithBackground(tui.NewStyle().Background(tui.Blue)),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
		)
		__tui_20 := tui.New(
			tui.WithText("⌨ c chats"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_19.AddChild(__tui_20)
		__tui_21 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_19.AddChild(__tui_21)
		__tui_22 := tui.New(
			tui.WithText("e edit"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_19.AddChild(__tui_22)
		__tui_23 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_19.AddChild(__tui_23)
		__tui_24 := tui.New(
			tui.WithText("esc back"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_19.AddChild(__tui_24)
		__tui_25 := tui.New(
			tui.WithText("•"),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_19.AddChild(__tui_25)
		__tui_26 := tui.New(
			tui.WithText("q quit"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_19.AddChild(__tui_26)
		if __tui_0 == nil {
			__tui_0 = __tui_19
		}
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = StatusBarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
