// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package database

import (
	"context"
)

const getOrCreateDirectConversation = `-- name: GetOrCreateDirectConversation :many
WITH
  existing AS (
    SELECT
      p1.conv_id
    FROM
      participants p1
      JOIN participants p2 ON p1.conv_id = p2.conv_id
    WHERE
      p1.user_id = $1
      AND p2.user_id = $2
    LIMIT
      1
  ),
  new_conv AS (
    INSERT INTO
      conversations (created_at)
    SELECT
      CURRENT_TIMESTAMP
    WHERE
      NOT EXISTS (
        SELECT
          1
        FROM
          existing
      )
    RETURNING
      id
  ),
  inserted_p1 AS (
    INSERT INTO
      participants (conv_id, user_id)
    SELECT
      id,
      $1
    FROM
      new_conv
  ),
  inserted_p2 AS (
    INSERT INTO
      participants (conv_id, user_id)
    SELECT
      id,
      $2
    FROM
      new_conv
  ),
  target_conv AS (
    SELECT
      conv_id AS id
    FROM
      existing
    UNION ALL
    SELECT
      id
    FROM
      new_conv
  )
SELECT
  tc.id AS conv_id,
  u.id AS user_id,
  u.name,
  u.username
FROM
  target_conv tc
  JOIN participants p ON p.conv_id = tc.id
  JOIN users u ON u.id = p.user_id
`

type GetOrCreateDirectConversationParams struct {
	UserID   int64
	UserID_2 int64
}

type GetOrCreateDirectConversationRow struct {
	ConvID   int64
	UserID   int64
	Name     string
	Username string
}

func (q *Queries) GetOrCreateDirectConversation(ctx context.Context, arg GetOrCreateDirectConversationParams) ([]GetOrCreateDirectConversationRow, error) {
	rows, err := q.db.Query(ctx, getOrCreateDirectConversation, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrCreateDirectConversationRow
	for rows.Next() {
		var i GetOrCreateDirectConversationRow
		if err := rows.Scan(
			&i.ConvID,
			&i.UserID,
			&i.Name,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
