// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID         int64
	IsDeleting bool
	CreatedAt  pgtype.Timestamptz
}

type Message struct {
	ID        int64
	SenderID  int64
	ConvID    int64
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Participant struct {
	ConvID            int64
	UserID            int64
	LastReadMessageID int64
	LastReadAt        pgtype.Timestamptz
}

type User struct {
	ID        int64
	Name      string
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UsersArchive struct {
	ID        int64
	Name      string
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
