// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (name, username, password)
VALUES
  ($1, $2, $3)
RETURNING
  id,
  name,
  username,
  created_at,
  updated_at
`

type CreateUserParams struct {
	Name     string
	Username string
	Password string
}

type CreateUserRow struct {
	ID        int64
	Name      string
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Username, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
  (id, name, username)
FROM
  users
WHERE
  username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (interface{}, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}
