// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (name, username, password)
VALUES
  ($1, $2, $3)
RETURNING
  id,
  name,
  username,
  created_at,
  updated_at
`

type CreateUserParams struct {
	Name     string
	Username string
	Password string
}

type CreateUserRow struct {
	ID        int64
	Name      string
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Username, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE
  id = $1
RETURNING
  id,
  name,
  username
`

type DeleteUserRow struct {
	ID       int64
	Name     string
	Username string
}

func (q *Queries) DeleteUser(ctx context.Context, id int64) (DeleteUserRow, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i DeleteUserRow
	err := row.Scan(&i.ID, &i.Name, &i.Username)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT 
  id, name, username, created_at, updated_at 
FROM 
  users 
WHERE 
  id = $1
`

type GetUserByIdRow struct {
	ID        int64
	Name      string
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
  id, name, username, password
FROM
  users
WHERE
  username = $1
`

type GetUserByUsernameRow struct {
	ID       int64
	Name     string
	Username string
	Password string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Password,
	)
	return i, err
}
