// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageAndGetRecipient = `-- name: CreateMessageAndGetRecipient :one
WITH
verified_sender AS (
    SELECT conv_id
    FROM
        participants
    WHERE
        user_id = $1
        AND conv_id = $2
),

recipient AS (
    SELECT user_id AS recipient_id
    FROM
        participants
    WHERE
        user_id <> $1
        AND conv_id = $2
    LIMIT
        1
),

inserted_msg AS (
    INSERT INTO
    messages (conv_id, sender_id, content)
    SELECT
        vs.conv_id AS conv_id,
        $1 AS sender_id,
        $3 AS content
    FROM
        verified_sender vs
    RETURNING
        id,
        conv_id,
        sender_id,
        content,
        created_at,
        updated_at
)

SELECT
    im.id,
    im.conv_id,
    im.sender_id,
    r.recipient_id,
    im.content,
    im.created_at,
    im.updated_at
FROM
    inserted_msg im
CROSS JOIN recipient r
`

type CreateMessageAndGetRecipientParams struct {
	SenderID pgtype.Int8
	ConvID   pgtype.Int8
	Content  pgtype.Text
}

type CreateMessageAndGetRecipientRow struct {
	ID          int64
	ConvID      int64
	SenderID    int64
	RecipientID int64
	Content     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateMessageAndGetRecipient(ctx context.Context, arg CreateMessageAndGetRecipientParams) (CreateMessageAndGetRecipientRow, error) {
	row := q.db.QueryRow(ctx, createMessageAndGetRecipient, arg.SenderID, arg.ConvID, arg.Content)
	var i CreateMessageAndGetRecipientRow
	err := row.Scan(
		&i.ID,
		&i.ConvID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversationById = `-- name: DeleteConversationById :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversationById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteConversationById, id)
	return err
}

const deleteMessagesAsBatch = `-- name: DeleteMessagesAsBatch :execrows
WITH batch AS (
    SELECT id FROM messages m
    WHERE m.conv_id = $1 LIMIT $2
)

DELETE FROM messages
WHERE id IN (SELECT id FROM batch)
`

type DeleteMessagesAsBatchParams struct {
	ConvID    int64
	BatchSize int64
}

func (q *Queries) DeleteMessagesAsBatch(ctx context.Context, arg DeleteMessagesAsBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessagesAsBatch, arg.ConvID, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConvChats = `-- name: GetConvChats :many
SELECT
    id,
    sender_id,
    content,
    created_at,
    updated_at
FROM
    messages
WHERE
    conv_id = $1
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    $2
`

type GetConvChatsParams struct {
	ConvID int64
	Limit  int64
}

type GetConvChatsRow struct {
	ID        int64
	SenderID  int64
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetConvChats(ctx context.Context, arg GetConvChatsParams) ([]GetConvChatsRow, error) {
	rows, err := q.db.Query(ctx, getConvChats, arg.ConvID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConvChatsRow
	for rows.Next() {
		var i GetConvChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConvChatsPaginated = `-- name: GetConvChatsPaginated :many
SELECT
    id,
    sender_id,
    content,
    created_at,
    updated_at
FROM
    messages
WHERE
    conv_id = $1
    AND (
        created_at < $2
        OR (
            created_at = $2
            AND id < $3
        )
    )
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    $4
`

type GetConvChatsPaginatedParams struct {
	ConvID    int64
	CreatedAt pgtype.Timestamptz
	ID        int64
	Limit     int64
}

type GetConvChatsPaginatedRow struct {
	ID        int64
	SenderID  int64
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetConvChatsPaginated(ctx context.Context, arg GetConvChatsPaginatedParams) ([]GetConvChatsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getConvChatsPaginated,
		arg.ConvID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConvChatsPaginatedRow
	for rows.Next() {
		var i GetConvChatsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationsByUserId = `-- name: GetConversationsByUserId :many
WITH
  target_conv AS (
    SELECT
      p.conv_id, c.created_at
    FROM
      participants p
      JOIN conversations c ON c.id = p.conv_id
    WHERE
      p.user_id = $1
      AND c.is_deleting = FALSE
  )
SELECT
  tc.conv_id,
  u.id AS user_id,
  u.name,
  u.username,
  COALESCE(lm.content, '') AS last_message,
  COALESCE(lm.created_at, tc.created_at) AS last_message_time,
  COALESCE(unread.count, 0)::int AS unread_count
FROM
  target_conv tc
  JOIN participants other_p ON other_p.conv_id = tc.conv_id
  AND other_p.user_id <> $1
  JOIN users u ON u.id = other_p.user_id
  JOIN participants my_p ON my_p.conv_id = tc.conv_id
  AND my_p.user_id = $1
  -- Latest message per conversation
  LEFT JOIN LATERAL (
    SELECT
      content,
      created_at
    FROM
      messages
    WHERE
      conv_id = tc.conv_id
    ORDER BY
      id DESC
    LIMIT
      1
  ) lm ON TRUE
  -- Unread messages since my last read watermark
  LEFT JOIN LATERAL (
    SELECT
      count(*) AS count
    FROM
      messages m
    WHERE
      m.conv_id = tc.conv_id
      AND m.id > my_p.last_read_message_id
      AND m.sender_id <> $1
  ) unread ON TRUE
ORDER BY
  COALESCE(lm.created_at, tc.created_at) DESC,
  tc.conv_id DESC
`

type GetConversationsByUserIdRow struct {
	ConvID          int64
	UserID          int64
	Name            string
	Username        string
	LastMessage     string
	LastMessageTime pgtype.Timestamptz
	UnreadCount     int32
}

func (q *Queries) GetConversationsByUserId(ctx context.Context, userID int64) ([]GetConversationsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getConversationsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsByUserIdRow
	for rows.Next() {
		var i GetConversationsByUserIdRow
		if err := rows.Scan(
			&i.ConvID,
			&i.UserID,
			&i.Name,
			&i.Username,
			&i.LastMessage,
			&i.LastMessageTime,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateDirectConversation = `-- name: GetOrCreateDirectConversation :many
WITH
existing AS (
    SELECT p1.conv_id
    FROM
        participants p1
    JOIN participants p2 ON p1.conv_id = p2.conv_id
    JOIN conversations c ON c.id = p1.conv_id
    WHERE
        p1.user_id = $1
        AND p2.user_id = $2
        AND c.is_deleting = FALSE
    LIMIT
        1
),

new_conv AS (
    INSERT INTO
    conversations (created_at)
    SELECT CURRENT_TIMESTAMP
    WHERE
        NOT EXISTS (
            SELECT 1
            FROM
                existing
        )
    RETURNING
        id
),

inserted_p1 AS (
    INSERT INTO
    participants (conv_id, user_id)
    SELECT
        id,
        $1
    FROM
        new_conv
),

inserted_p2 AS (
    INSERT INTO
    participants (conv_id, user_id)
    SELECT
        id,
        $2
    FROM
        new_conv
),

target_conv AS (
    SELECT conv_id AS id
    FROM
        existing
    UNION ALL
    SELECT id
    FROM
        new_conv
)

SELECT
    tc.id AS conv_id,
    u.id AS user_id,
    u.name,
    u.username
FROM
    target_conv tc
JOIN participants p ON p.conv_id = tc.id
JOIN users u ON u.id = p.user_id
`

type GetOrCreateDirectConversationParams struct {
	UserID   int64
	UserID_2 int64
}

type GetOrCreateDirectConversationRow struct {
	ConvID   int64
	UserID   int64
	Name     string
	Username string
}

func (q *Queries) GetOrCreateDirectConversation(ctx context.Context, arg GetOrCreateDirectConversationParams) ([]GetOrCreateDirectConversationRow, error) {
	rows, err := q.db.Query(ctx, getOrCreateDirectConversation, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrCreateDirectConversationRow
	for rows.Next() {
		var i GetOrCreateDirectConversationRow
		if err := rows.Scan(
			&i.ConvID,
			&i.UserID,
			&i.Name,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCountForUser = `-- name: GetUnreadCountForUser :one
SELECT
  COUNT(*)::int AS unread_count
FROM
  messages m
  JOIN participants p ON p.conv_id = m.conv_id
  AND p.user_id = $1
WHERE
  m.conv_id = $2
  AND m.id > p.last_read_message_id
  AND m.sender_id <> $1
`

type GetUnreadCountForUserParams struct {
	UserID int64
	ConvID int64
}

func (q *Queries) GetUnreadCountForUser(ctx context.Context, arg GetUnreadCountForUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUnreadCountForUser, arg.UserID, arg.ConvID)
	var unread_count int32
	err := row.Scan(&unread_count)
	return unread_count, err
}

const isUserInConversation = `-- name: IsUserInConversation :one
SELECT EXISTS(
    SELECT 1 FROM participants
    WHERE conv_id = $1 AND user_id = $2
)
`

type IsUserInConversationParams struct {
	ConvID int64
	UserID int64
}

func (q *Queries) IsUserInConversation(ctx context.Context, arg IsUserInConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInConversation, arg.ConvID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markConversationDeleting = `-- name: MarkConversationDeleting :exec
UPDATE conversations c SET is_deleting = TRUE
WHERE c.id = $1
`

func (q *Queries) MarkConversationDeleting(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markConversationDeleting, id)
	return err
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE participants
SET
  last_read_message_id = GREATEST(
    last_read_message_id,
    CASE
      WHEN $1::bigint > 0 THEN $1::bigint
      ELSE COALESCE((SELECT MAX(id) FROM messages WHERE conv_id = $2), 0)
    END
  ),
  last_read_at = NOW()
WHERE
  conv_id = $2
  AND user_id = $3
`

type MarkConversationReadParams struct {
	MessageID int64
	ConvID    int64
	UserID    int64
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.MessageID, arg.ConvID, arg.UserID)
	return err
}
